dependencies:

  - name: kube-state-metrics
    version: 2.3.*
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: kubeStateMetrics.enabled

  - name: prometheus-node-exporter
    version: 1.5.*
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: nodeExporter.enabled

  - name: grafana
    version: 3.8.*
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: grafana.enabled

  - name: prometheus-process-exporter
    version: 0.1.0
    repository: http://localhost:8879/charts
    condition: processExporter.enabled

  - name: prometheus-openstack-exporter
    version: 0.1.0
    repository: http://localhost:8879/charts
    codition: openstackExporter.enabled
