{{- if and .Values.elasticsearchOperator.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-secret
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eck.name" . }}-operator
  namespace: {{ .Release.Namespace }}
---
{{- end }}
